name: C++ Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure CMake (Windows with MinGW)
        if: runner.os == 'Windows'  # 仅在 Windows 运行
        run: cmake -G "MinGW Makefiles" -B build -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

      - name: Configure CMake (Other OS)
        if: runner.os != 'Windows'  # 仅在 Linux/macOS 运行
        run: cmake -B build -DCMAKE_INSTALL_PREFIX=.
      - name: Build Project
        run: cmake --build build --config Release

      - name: Install Project
        run: cmake --install build

      - name: Upload Executable (if master branch)
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: nst-${{ runner.os }}
          path: bin/nst*
